[package]
name = "hi"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
axum-kit = "0.6"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread"] }
tower = "0.5"
